version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_turnoverme
    restart: unless-stopped
    ports:
      - "65432:5432"
    environment:
      POSTGRES_USER: turnoverme
      POSTGRES_PASSWORD: turnoverme
      POSTGRES_DB: turnoverme
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
